ShowMeSchool/urls.py
# ShowMeSchool/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('project.urls')),
    path('users/', include('users.urls')),
]

project/urls.py
# project/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

project/models.py
from django.db import models

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

project/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'project/index.html')

users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from users.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'users/signup.html', {'form': form})

project/templates/project/index.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>ShowMeSchool !!!</title>

    <style>

        html, body {
            height: 100%;
        }

        .wrap {
            position: relative;
            min-height: 100%;
            padding-bottom: 114px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            background-color: lavender;
            width: 100%;
            border-radius: 0px 60px 0px 0px;
            text-align: center;
        }


    </style>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
</head>
<body style="background : rgba(255, 255, 255, 0.91);">

<div class="wrap">
    <div>
        <div style=" border:4px solid mediumpurple; background-color: mediumpurple">
            <!--검색-->
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search"
                       aria-label="Search"
                       style="height: 60px ;background-color: floralwhite ;">
                <button class="btn btn-outline-success" type="submit" style="height: 60px ;background-color: lavender">
                    Search
                </button>
            </form>
            <!-- 검색 -->
        </div>
        <!--네비바-->

        <div style="background-color:#7c1772;height: 110px ;border-radius: 0px 0px 0px 60px;">
            <a href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" width="280px" height="70px"
                                             style="margin-left: 15px;margin-top: 6px"></a>

            <div style="text-align: right; margin-top: -50px;margin-right: 30px">

                {% if user.is_authenticated %}
                    <a style="font-size: 25px;text-decoration-line: none;color: #ef86f1"
                       href="{% url 'users:logout' %}"><strong>{{ user.username }} (로그아웃)</strong></a>

                {% else %}
                    <a style="font-size: 25px;text-decoration-line: none;color: #ef86f1"
                       href="{% url 'users:login' %}"><strong>로그인</strong></a>
                {% endif %}
                <div style="float: right;">
                    {% if not user.is_authenticated %}
                        <a style="font-size: 25px;text-decoration-line: none;color: #ef86f1" class="nav-link"
                           href="{% url 'users:signup' %}"><strong> &nbsp;&nbsp;| &nbsp;회원가입</strong></a>
                    {% endif %}
                </div>
            </div>
        </div>

        <!--네비바-->
    </div>
    <!--사이드바-->
    <div class="container-fluid" style="height: 800px;margin-bottom: 5%">
        <div class="row flex-nowrap" style="height: 800px">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark"
                 style="border-top: 7px solid black;border-bottom: 9px solid black;margin:2% 0% 0% 2%;">
                <div class="dropdown pb-4" style="height: 100px">
                    <a href="#" class="d-flex align-items-center text-#ef86f1 text-decoration-none dropdown-toggle"
                       id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="hugenerd" width=70" height="70"
                             class="rounded-circle">
                        <span style="color: #ef86f1;font-size: 30px" class="d-none d-sm-inline mx-1">loser</span>
                    </a>

                </div>
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white "
                     style="background-color:lavenderblush; border-top: 4px solid lavenderblush;height: 80%">
                    <a href="/"
                       class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline" style="color:#ef86f1 ">Menu</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                        id="menu">
                        <li class="nav-item">
                            <a href="#" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        <li>
                            <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-speedometer2"></i> <span
                                    class="ms-1 d-none d-sm-inline">Dashboard</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                    </li>

                    </ul>
                    <hr>

                </div>
            </div>
            <div class="col py-3">
                <!--컨텐츠-->
                {#                <div style="width:500px; height:600px; border:7px solid #7c1772; float:left; margin:5% 5% 0% 5%">#}
                {##}
                {#                </div>#}

                {#                <div style="width:500px; height:600px; border:7px solid #7c1772; float:left;margin:5% 5% 0% 5%">#}
                {##}
                {#                </div>#}
                {##}

                <div style="width:40%; height:75%; border:7px solid #7c1772; float:left; margin:4% 5% 0% 5%">

                    <div class="card" style="width: 50%;height: 50%;float: left;">
                        <img src="{% static 'images/school1.jpeg' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body" style="">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>

                    <div class="card" style="width: 50%;height: 50%">
                        <img src="{% static 'images/school1.jpeg' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>

                    <div class="card" style="width: 50%;height: 50%;float: left">
                        <img src="{% static 'images/school1.jpeg' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body" style="">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>

                    <div class="card" style="width: 50%;height: 50%">
                        <img src="{% static 'images/logo.png' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>
                </div>


                <div style="width:40%; height:75%; border:7px solid #7c1772; float:left;margin:4% 5% 0% 5%">
                    <div class="card" style="width: 50%;height: 50%;float: left;">
                        <img src="{% static 'images/school1.jpeg' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body" style="">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>

                    <div class="card" style="width: 50%;height: 50%">
                        <img src="{% static 'images/school1.jpeg' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>

                    <div class="card" style="width: 50%;height: 50%;float: left">
                        <img src="{% static 'images/school1.jpeg' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body" style="">
                            <p class="card-text" style="'"><strong>경기고등학교</strong></p>
                        </div>
                    </div>

                    <div class="card" style="width: 50%;height: 50%">
                        <img src="{% static 'images/logo.png' %}" width="100%"
                             height="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text" style=""><strong>경기고등학교</strong></p>
                        </div>
                    </div>
                </div>
                <!--컨텐츠-->
            </div>

        </div>
    </div>
    <!--사이드바-->
    <div class="footer">
        <footer>
            <nav style="margin-top: 1%">
                <a href='https://backendjun.tistory.com' target='_blank'>Blog</a> |
                <a href='https://github.com/PHJ1216' target='_blank'>Github</a>
            </nav>
            <p>
                <span>저자 : ParkHyeonJun</span><br/>
                <span>이메일 :phjapark@naver.com</span><br/>
                <span>Copyright 2023. ParkHyeonJun. All Rights Reserved.</span>
            </p>
        </footer>
    </div>
</div>
</body>
</html>

users/templates/users/form_errors.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
</head>
<body>
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger" style="background-color: lavender; margin-top: 3%">
        {% for field in form %}
            <!-- 필드 오류 [필드 오류는 사용자가 입력한 필드 값에 대한 오류로 값이 누락되었거나 필드의 형식이 일치하지 않는 경우에 발생하는 오류이다.] -->
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!-- 넌필드 오류 [넌필드 오류는 필드의 값과는 상관없이 다른 이유로 발생하는 오류이다.]-->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}



</body>
</html>

users/templates/users/login.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>ShowMeSchool !!!</title>
    <style>
        html, body {
            height: 100%;
        }

        .wrap {
            position: relative;
            min-height: 100%;
            padding-bottom: 114px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            background-color: lavender;
            width: 100%;
            border-radius: 0px 60px 0px 0px;
            text-align: center;
        }

    </style>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
</head>
<body>
<div class="wrap">
    <div>
        <div style=" border:4px solid mediumpurple; background-color: mediumpurple">
            <!--검색-->
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search"
                       aria-label="Search"
                       style="height: 60px ;background-color: floralwhite ;">
                <button class="btn btn-outline-success" type="submit" style="height: 60px ;background-color: lavender">
                    Search
                </button>
            </form>
            <!-- 검색 -->
        </div>

        <!--네비바-->
        <div style="background-color:#7c1772;height: 110px ;border-radius: 0px 0px 0px 60px;">
            <a href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" width="280px" height="70px"
                                             style="margin-left: 15px;margin-top: 6px" href="www.naver.com"></a>
        </div>
        <!--네비바-->
    </div>

    <!--로그인-->


    {% block content %}
        <div class="container my-3">
            <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                {% include "users/form_errors.html" %}

                <div class="mb-3" style="">
                    <label for="username" style="font-size: 25px">사용자ID</label>
                    <input type="text" class="form-control" name="username" id="username"
                           style="border: 5px Solid mediumpurple"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password" style="font-size: 25px">비밀번호</label>
                    <input type="password"w class="form-control" name="password" id="password"
                           style="border: 5px Solid mediumpurple"
                           value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-primary"
                        style="border: 5px Solid mediumpurple; background-color:mediumpurple"><strong>로그인</strong>
                </button>
            </form>
        </div>
    {% endblock %}

    <!--로그인-->
    <div class="footer">
        <footer>
            <nav style="margin-top: 1%">
                <a href='https://backendjun.tistory.com' target='_blank'>Blog</a> |
                <a href='https://github.com/PHJ1216' target='_blank'>Github</a>
            </nav>
            <p>

                <span>저자 : ParkHyeonJun</span><br/>
                <span>이메일 :phjapark@naver.com</span><br/>
                <span>Copyright 2023. ParkHyeonJun. All Rights Reserved.</span>
            </p>
        </footer>
    </div>
</div>
</body>
</html>

users/templates/users/signup.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>ShowMeSchool !!!</title>
    <style>
        html, body {
            height: 100%;
        }

        .wrap {
            position: relative;
            min-height: 100%;
            padding-bottom: 114px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            background-color: lavender;
            width: 100%;
            border-radius: 0px 60px 0px 0px;
            text-align: center;
        }

    </style>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
</head>
<body>
<div class="wrap">
    <div>
        <div style=" border:4px solid mediumpurple; background-color: mediumpurple">
            <!--검색-->
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search"
                       aria-label="Search"
                       style="height: 60px ;background-color: floralwhite ;">
                <button class="btn btn-outline-success" type="submit" style="height: 60px ;background-color: lavender">
                    Search
                </button>
            </form>
            <!-- 검색 -->
        </div>

        <!--네비바-->
        <div style="background-color:#7c1772;height: 110px ;border-radius: 0px 0px 0px 60px;">
            <a href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" width="280px" height="70px"
                                             style="margin-left: 15px;margin-top: 6px" href="www.naver.com"></a>
        </div>
        <!--네비바-->
    </div>

    <!--회원가입-->

    {% block content %}
        <div class="container my-3">
            <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                {% include "users/form_errors.html" %}
                <div class="mb-3">
                    <label for="username" style="font-size: 25px">사용자 이름</label>
                    <input type="text" class="form-control" name="username" id="username"
                           style="border: 5px Solid mediumpurple"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password1" style="font-size: 25px">비밀번호</label>
                    <input type="password" class="form-control" name="password1" id="password1"
                           style="border: 5px Solid mediumpurple"
                           value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password2" style="font-size: 25px">비밀번호 확인</label>
                    <input type="password" class="form-control" name="password2" id="password2"
                           style="border: 5px Solid mediumpurple"
                           value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="email" style="font-size: 25px">이메일</label>
                    <input type="text" class="form-control" name="email" id="email"
                           style="border: 5px Solid mediumpurple"
                           value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-primary"
                        style="border: 5px Solid mediumpurple; background-color:mediumpurple"><strong>생성하기</strong>
                </button>
            </form>
        </div>
    {% endblock %}

    <!--회원가입-->
    <div class="footer">
        <footer>
            <nav style="margin-top: 1%">
                <a href='https://backendjun.tistory.com' target='_blank'>Blog</a> |
                <a href='https://github.com/PHJ1216' target='_blank'>Github</a>
            </nav>
            <p>
                <span>저자 : ParkHyeonJun</span><br/>
                <span>이메일 :phjapark@naver.com</span><br/>
                <span>Copyright 2023. ParkHyeonJun. All Rights Reserved.</span>
            </p>
        </footer>
    </div>
</div>
</body>
</html>